server:
  port: 8081
spring:
  webflux:
    base-path: /resume
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/rocketservice
    username: postgres
    password: rocketpass
  datasource:
    url: jdbc:postgresql://localhost:5432/rocketservice
    username: postgres
    password: rocketpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml